### ISSUE TITLE
[Breaking] The script will not work when loaded from nginx because of the ಠ character

### ISSUE THREAD

**Issue by gabrieli** [bfred-it/iphone-inline-video#100]
I used your package (thanks for making it) as a dependency. When loading and serving the whole package from an nginx server, I get the following error in the console: 
"Uncaught SyntaxError: Invalid or unexpected token" pointing to  var ಠ = Symbol(); which is actually malformed to var à² = Symbol(). 

The nginx is a fresh install following this guide: https://gist.github.com/netpoetica/5879685

It could potentially be nginx not liking that char, and a conf issue, but when this code will be served as a 3rd party, without me having control of the servers serving it. 

On node it works fine. 

Thanks!

**Comment by bfred-it** [comment]
You should serve the monitors version which does not contain that character. Also the issue is probably caused by your server: you need to set it to deliver UTF-8
