### ISSUE TITLE
Poster image seems to be cached

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#102]
This one is hard to reproduce. How to explain?

I've got few emails in my inbox, each of them has a video in it. When I open the first email, my iPhone loads the poster image for the video fine and I can play the video.

But when I open the second email that has a different poster and video in it, I still see the poster of the first video. Looks like it caches the first poster and uses that for all other videos.

**Comment by bfred-it** [comment]
Please use the correct terms. IIV doesn't run in email clients so you're not exactly opening emails.

Do these videos live on some website?
When you say "open the second email", are you opening a second link that is its own tab/page/history?

**Comment by binarykitchen** [comment]
silly me, this has nothing to do with IIV since it's apple's default mail client caching the poster image. i ll have to report this to them.

sorry + closing
