### ISSUE TITLE
iPad autoplay fail

### ISSUE THREAD

**Issue by bquarante** [bfred-it/iphone-inline-video#103]
on branch 2.0 :
iPad autoplay don't work... but i see the first image of the video
i use the iPad param (enableInlineVideo(video, { iPad: true }); )

Checking the ipad safari console via my macbook,
i can see an error on line 104 : if (void 0 === i && (i = {}), !e[y]) {
it says : null is not an object (evaluating 'y') 

i'm on iOS 9.3.5

Any idea?

(Thank you so much for this work btw)

**Comment by bquarante** [comment]
my bad, io just forgot to put enableInlineVideo(video, { iPad: true }); before the /body

**Comment by bfred-it** [comment]
Thanks for reporting! 

v2.0.0 has been published now :)
