### ISSUE TITLE
Streamin URL 

### ISSUE THREAD

**Issue by jarangseo** [bfred-it/iphone-inline-video#106]
Dear Super Developer,
Hello im jarangseo : )
I also love this polyfill thank u for nice code for playsinline.
But i got an issue for using this.
when i use Streaming URL, there are so many buffers during playing.
The url that i used is below.
"http://edge2.everyon.tv/etv2/phd133/playlist.m3u8?country=KR&category=0500&protocol=hls&quality=0&channel=133&player=web&network=pc&p2pupuser=off&domain=everyon&bitrate=896&server=org"
Could u give me some clues for this problem?
Warm regards, jarang.

**Comment by bfred-it** [comment]
Refer to #4

Unfortunately streaming is not supported
