### ISSUE TITLE
Video plays really slow and not until the end

### ISSUE THREAD

**Issue by nessyta** [bfred-it/iphone-inline-video#107]
I've updated to the last version because the previous one was having problems with promises, and now the videos are playing really slow and some of them not to their full length.

I'm using this to init the inline videos
`$('video').each(function () {
    enableInlineVideo(this, { iPad: true });
  });`

and **webkit-playsinline playsinline** on muted video tags.

I don't know if it has a conecction or not, but I have 3 players running one after ther other, like a slider. If I comment out **enableInlineVideo** line, the videos play as they should, but fullscreen on iOS.

Is there something I'm missing?

**Comment by bfred-it** [comment]
I don't think IIV ever used promises. 

Can you post your website so I can take a look?

**Comment by nessyta** [comment]
i'm testing in both iOS 8  and 9 with browserstack and with the chrome emulator.
I can't post the url of the website because of a no disclosure agreement as it's still on development status.

> I don't think IIV ever used promises.
that's odd then, it suddenly started triggering a promise not handled.

Since posting this here I made some tests and found that it must be something in my code

**Comment by bfred-it** [comment]
That promise issue was possibly Chrome-only. Try the older version again and let me know if that works. Without taking a look at the website I really can't help you with this unfortunately.
