### ISSUE TITLE
how to use with React Player ?

### ISSUE THREAD

**Issue by jasan-s** [bfred-it/iphone-inline-video#108]

**Comment by bfred-it** [comment]
I don't know React Player. Provide your current React Player code and I'll see where to place IIV

**Comment by jasan-s** [comment]
`import React, { Component } from 'react'
import ReactPlayer from 'react-player'

class App extends Component {
  render () {
    return <ReactPlayer url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' playing />
  }
}`

**Comment by bfred-it** [comment]
I'm not sure. Perhaps ask in React Player's repo. 

IIV needs to run soon after the <video> element is created and before RPlayer attaches any events to it. It depends on how they implemented it.
