### ISSUE TITLE
Did it done in Wechat of China?

### ISSUE THREAD

**Issue by evenle** [bfred-it/iphone-inline-video#109]
How about Wechat?Can it run?
The browser in  Chinese Wechat is different.It is always not the same in different versions.
Do you have to follow the version of WeChat updates?
Thanks!

**Comment by bfred-it** [comment]
Can you test this page on WeChat on iOS 9? Does it autoplay? http://bfred-it.github.io/iphone-inline-video/demo/

I cannot test it
