### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#11]
```
videomail-client@1.9.8 test /home/michael-heuberger/Development/videomail-client
tape test/**/*.test.js

/home/michael-heuberger/Development/videomail-client/node_modules/iphone-inline-video/dist/iphone-inline-video.common-js.js:74
var isNeeded = /iPhone|iPod/i.test(navigator.userAgent);
                                   ^
ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/michael-heuberger/Development/videomail-client/node_modules/iphone-inline-video/dist/iphone-inline-video.common-js.js:74:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/michael-heuberger/Development/videomail-client/src/wrappers/visuals/replay.js:3:31)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by bfred-it** [comment]
This library is meant to run in a browser environment and soon enough you will find that Audio, document and many other absolutely necessary variables will fail your tests. On second thought I will probably revert #10 too

**Comment by binarykitchen** [comment]
@bfred-it please don't revert. otherwise i ll have to delete all unit tests in my library or add ugly hacks :(

i think it is important that your code does not crash in a nodejs environment or at least skips. how else can others then run their unit tests?

furthermore i think the boundaries between browser and nodejs environment are getting blurry these days.

**Comment by bfred-it** [comment]
I'm all up for tests but they need to make sense. Simply have it skip browser-only units because why test something that can't be tested? It sounds like a waste of time for everyone involved.

If you insist it's up to you to "polyfill" the browser environment into node, sort of like browserify does the opposite. I'm almost too byte-conscious to add any other checks.

**Comment by binarykitchen** [comment]
@bfred-it you have a good point. I ll have a good think about this and come back to you.

**Comment by bfred-it** [comment]
Here's the polyfill I was talking about https://github.com/lukechilds/node-browser-environment

**Comment by binarykitchen** [comment]
interesting package - why not?
