### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import in iphone-inline-video when transferred to codeigniter framework

### ISSUE THREAD

**Issue by windchime18** [bfred-it/iphone-inline-video#110]
How come when I deploy it on my codeigniter framework it doesn't work? It displays an error in javascript on my console. 

`Uncaught SyntaxError: Unexpected token import index.js:1`

`import {frameIntervalometer} from 'intervalometer';`
`import preventEvent from '../../assets/lib/prevent-event';`
`import proxyProperty from '../../assets/lib/proxy-property';`
`import proxyEvent from '../../assets/lib/proxy-event';`
`import dispatchEventAsync from '../../assets/lib/dispatch-event-async';`

**Comment by bfred-it** [comment]
Are you using browserify/webpack? If not, you need to use the files in the DIST folder, like https://github.com/bfred-it/iphone-inline-video/blob/master/dist/iphone-inline-video.min.js

**Comment by windchime18** [comment]
thanks. it worked :)
