### ISSUE TITLE
Setting of volume or mute/unmute while playing is not working.

### ISSUE THREAD

**Issue by windchime18** [bfred-it/iphone-inline-video#111]
Is it possible to unmute or change the volume while playing the video? I have tried it but it wont work.

`var video = document.querySelector('video');`
`enableInlineVideo(video);`
`video.addEventListener('touchstart', function () {`
`if (video.paused === false) {`
			    	`video.pause();`
			  `  }`
			`    else{`
			    	`video.play();`
			`    }`
			`});`
			`$('#volume').on('change', function() {`
				`$("#video").removeAttr('muted');`
			    `video.volume=this.value;`
			`    console.log(video.volume);`
			`});`

`<video id="video" autoplay muted  playsinline src="file.mp4"></video>`
				`<br><br>`
				`<div id="video-controls">`
				`    <input type="range" id="volume" min="0" max="1" step="0.1" value="1" />`
			`	</div>`

**Comment by bfred-it** [comment]
iOS does not support volume changes. 

Mute toggling is tracked in #56

**Comment by windchime18** [comment]
Thank you for your prompt reply. :) 👍
