### ISSUE TITLE
2 live streams can't play together?

### ISSUE THREAD

**Issue by KilianPauwels** [bfred-it/iphone-inline-video#112]
Hi,
I'm trying to make an application where 2 live streams would be playing side by side. When I test this they both start playing but the second one freezes on the first frame. Current time of both is getting updated so I don't understand what's going on and thought maybe you could help. When I test with one livestream and one video on demand they both play like normal.

Thanks a lot.

**Comment by bfred-it** [comment]
Live streams are not supported by IIV on iOS 9: #4

Are you testing this on iOS 9?

**Comment by bfred-it** [comment]
Live streams are not supported by IIV on iOS 9: #4

Are you testing this on iOS 9?

**Comment by KilianPauwels** [comment]
No, I'm testing on ios10 with this code segment I found in another issue.

                enableInlineVideo(video2, {
    		        everywhere: /iPhone|iPad|iPod/i.test(navigator.userAgent)
		});
		enableInlineVideo(video1, {
    		        everywhere: /iPhone|iPad|iPod/i.test(navigator.userAgent)
		});

**Comment by bfred-it** [comment]
I'm surprised that it works at all since IIV does not work with live streams. In your case the videos might be working separately because iOS 10 is playing them, not IIV, which would explain why only one at a time can play (standard iOS limitation)

**Comment by KilianPauwels** [comment]
Okay thank you very much!
