### ISSUE TITLE
Video doesn't play inline on Firefox Mobile

### ISSUE THREAD

**Issue by r-michel** [bfred-it/iphone-inline-video#114]
The video doesn't play inline and can only be played full screen on Firefox Mobile (trie on iOs, probably the same on Android). It works great on other browsers.

**Comment by bfred-it** [comment]
Did you try on iOS 9?

**Comment by r-michel** [comment]
I tried on IOS10. I sadly no longer have the ios device to try the demo, so I can't test it.

**Comment by bfred-it** [comment]
Firefox 7.5 on iOS 10

[![gif](https://giant.gfycat.com/NiceSnoopyBernesemountaindog.gif)](https://gfycat.com/NiceSnoopyBernesemountaindog)
