### ISSUE TITLE
Not working with iOS 10.3.1 Update?

### ISSUE THREAD

**Issue by panalex1982** [bfred-it/iphone-inline-video#118]
After updating to iOS 10.3.1 (Checked on iPhone 6 simulator and iPod 6)  the videos which was working well inline in my application, now they are playing only as full screen. Although the demo (https://bfred-it.github.io/iphone-inline-video/demo/) on Safari plays inline. Has something changed with the last iOS? Did you notice something similar?

**Comment by bfred-it** [comment]
iphone-inline-video is only for iOS 8 and iOS 9. 

On iOS 10 you only need the `playsinline` attribute. 

Please refer to the readme.

**Comment by willvedd** [comment]
@panalex1982 thanks for creating this issue. I had the same issue and it wasn't immediately obvious what the issue was.
