### ISSUE TITLE
Not working in WeChat

### ISSUE THREAD

**Issue by DarwinniwraD** [bfred-it/iphone-inline-video#120]
I visited the demo inside a Wechat APP, but not working

**Comment by bfred-it** [comment]
WeChat on iOS 10 does not need IIV. However, WeChat does not support autoplay. I suggest you contact the WeChat team to enable this feature.

Test without IIV: https://codepen.io/anon/pen/MmPVNo

Screencast on iOS 10 / WeChat 6.5.8:

[![gif](https://fat.gfycat.com/RapidFemaleGenet.gif)](https://gfycat.com/RapidFemaleGenet)
