### ISSUE TITLE
Replace ಠ with IIV?

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#128]
Initially suggested in https://github.com/rollup/rollup/issues/1345#issuecomment-310298004, I am happy to submit a PR to replace all occurrences of character 'ಠ' (U+0CA0) with IIV.

But first I'd like to know why that character was chosen and if it has a special meaning? Probably for some browsers forcing to escape certain code routine?

**Comment by bfred-it** [comment]
# ಠ_ಠ

Here's the special meaning. It's an eye and it's used for lookup. 😅

**Comment by binarykitchen** [comment]
ha, cool ... and what you mean with lookup?

**Comment by bfred-it** [comment]
[Lookup table](https://www.wikiwand.com/en/Lookup_table)

Not sure if it's the right term, but it was a pun-variable.

**Comment by binarykitchen** [comment]
Here u go https://github.com/bfred-it/iphone-inline-video/pull/130

**Comment by bfred-it** [comment]
2.2.2 coming!
