### ISSUE TITLE
[iOS] Autoplay doesn't work with css prop display:none

### ISSUE THREAD

**Issue by rikardjh** [bfred-it/iphone-inline-video#131]
Just a heads up for the demo. Seems like the autoplay doesn't work in demo/threejs.html when hiding the video with display:none. Just gives a black page.

Quick workaround is changing the css to opacity:0;position:fixed;

iOS version 11.0 (beta) and 10.3.2

**Comment by bfred-it** [comment]
Thanks for the issue, I think this is a iOS regression bug. Can you report it to WebKit?
