### ISSUE TITLE
Would this library work on non-webGL devices?

### ISSUE THREAD

**Issue by Richacinas** [bfred-it/iphone-inline-video#133]
Hello there,

I'm just wondering if I could reliably use this library on older devices. I need to make sure that I provide a wide solution and wouldn't like to use a disclaimer so people using a low quality or older device cannot use my video experience.

Thanks a lot

**Comment by bfred-it** [comment]
Yes, it does not use WebGL.

**Comment by Richacinas** [comment]
Alright, my mistake.

So, it contains the necessary JS to allow the video work inline on iOS. What about iOS 10?

**Comment by jsiebern** [comment]
https://github.com/bfred-it/iphone-inline-video#notes-about-ios-10

It's right there in the docs ;-)
