### ISSUE TITLE
option to force IIV to be used on iOS 11 when in low power mode

### ISSUE THREAD

**Issue by rformato** [bfred-it/iphone-inline-video#136]
On iOS 11+ (not iOS 10) when in low power mode the autoplay is forbidden.
It might be interesting adding an option to force iphone-inline-video even for ios11 when in low power mode. That can be detected

**Comment by bfred-it** [comment]
I’m not particularly keen on overriding a behavior specifically made to save battery… by using a whole lot more battery with JavaScript playback. I’m gonna pass on this.

I consider IIV to be a polyfill at this point and as such it should stop existing when iOS 9 stops being supported.
