### ISSUE TITLE
vpaid enabled ?

### ISSUE THREAD

**Issue by giannoudak** [bfred-it/iphone-inline-video#137]
Hello bfred!

Can your plugin be used with the vpaid protocol? we are using the [videojs-vpaid-plugin](https://github.com/MailOnline/videojs-vast-vpaid) to make our video player vpaid enabled. 

We give the plugin a video element as input  and then do all the vpaid handshake actions (handshake, init, load, etc...) 

In which event we should call the enableInlineVideo plugin?

For your information, i can't control the vpaid creative code. its comes from third party demand

thanks in advance

**Comment by bfred-it** [comment]
I don't know about `vpaid` specifically. `IIV` should be enabled as soon as possible after the `<video>` element has been created.
