### ISSUE TITLE
Error DOMException

### ISSUE THREAD

**Issue by SoyAndresHernandez** [bfred-it/iphone-inline-video#138]
Hello mate. I am using react and I have this error. Does anyone know what is going on ?

`:3000/#:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

**Comment by bfred-it** [comment]
I’d need your full code. Are you using `<source>` and/or changing the `src` after initialization?

**Comment by jsiebern** [comment]
I found it to not work with react when I tried it a while back, my solution was to create a div and manually create the video element and inserting it into the react div. It's a bit dirty but it did the trick just fine.

**Comment by bfred-it** [comment]
If anyone provides a repro I can look into it.

There are other issues opened by people trying it with react, maybe they have the solution.

**Comment by bfred-it** [comment]
I’m sure that’s unnecessary, you need to IIV on the real dom element, not on the react component. IIV should not go through React so there’s no prop that it wouldn’t “pass”

**Comment by montogeek** [comment]
We do it like this:
```
 initPolyfill(this.video, {
        iPad: true,
        muted: this.state.muted
      })
```

Where `this.video` is a ref

**Comment by bfred-it** [comment]
A ref to what?

Muted isn’t a parameter anymore, it just reads the attribute.

**Comment by montogeek** [comment]
@bfred-it https://reactjs.org/docs/refs-and-the-dom.html, I am not the original issue autor, just trying to help how to integrate your library with React.

**Comment by bfred-it** [comment]
@montogeek Thanks, the sounds like the correct way.

Still more context is needed. https://jsfiddle.net/
