### ISSUE TITLE
Loop?

### ISSUE THREAD

**Issue by positlabs** [bfred-it/iphone-inline-video#14]
Seems like the loop attribute isn't supported. Is this true?

**Comment by bfred-it** [comment]
I added it in a test version, can you try this?
https://raw.githubusercontent.com/bfred-it/iphone-inline-video/90e437733e67b7209c2f07972c3002f9aec54111/dist/iphone-inline-video.browser.js

**Comment by positlabs** [comment]
Works perfectly! Thanks!
