### ISSUE TITLE
Common and es modules

### ISSUE THREAD

**Issue by zouloux** [bfred-it/iphone-inline-video#140]
Hello and thanks for this very useful library !

I'm just wondering. Why common-js and es-modules are gitignore ? It force us to build or fork it to have these files with npm.

Thanks !

**Comment by bfred-it** [comment]
No, those files are ignored from git, but they are on npm 😉

**Comment by zouloux** [comment]
Why I didn't saw them. Thanks for your time :) I'll remove my useless fork.
