### ISSUE TITLE
Failed to set currentTime 

### ISSUE THREAD

**Issue by positlabs** [bfred-it/iphone-inline-video#15]
I'm getting an error while using chrome's devtools in device mode.

Super minor bug, but makes testing in general slightly more difficult.

![screen shot 2016-04-11 at 3 34 09 pm](https://cloud.githubusercontent.com/assets/1918844/14444636/a25536d0-fffb-11e5-8082-58ac99f1a5b7.png)

**Comment by positlabs** [comment]
I'm not setting this value anywhere in my code.

This is the only line that references the video.

```
makeVideoPlayableInline($('.vid')[0], false);
```

**Comment by bfred-it** [comment]
Ah I see what you mean now. I think you can't use Chrome's Dev tools to test it because of how they handle a few things differently from Safari. You might just have to use Safari Remote Debug

**Comment by bfred-it** [comment]
Can you verify that the video is being loaded correctly? I saw that issue when the video failed to load and therefore `video.currentTime` is NaN
