### ISSUE TITLE
Videomails can't be played on iPhones

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#16]
Hello again

I have added your library to my web app for recording videos online, see https://www.videomail.io
But it seems your library still can't help playing the recorded videos for iPhones.

How to reproduce:
1. Just record a videomail from that page
2. Send it to yourself
3. Open that videomail on your iPhone mail app
4. Click on the link and it should open the view page on Safari
5. But no picture, no video, nothing.

Any ideas why?

**Comment by bfred-it** [comment]
`iphone-inline-video` is javascript
Most email clients don't support javascript

**Comment by binarykitchen** [comment]
No, not email. Just click on the link in the email to open the web page. Video won't play on Safari.

**Comment by bfred-it** [comment]
My bad, I'm seeing that now. Make sure that you call `makeVideoPlayableInline()` **after** setting the `src` to the video

**Comment by bfred-it** [comment]
Actually, I'm not seeing the props on the `<video>` element at all, so make sure that the function is actually called

**Comment by binarykitchen** [comment]
ok, will try tomorrow, thanks

**Comment by binarykitchen** [comment]
@bfred-it Hmmm, I moved `makeVideoPlayableInline` after setting the src's to the video. Still no luck. 

See changes at
https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/replay.js#L92

that show() function is called after mp4 + webm sources are set.

Have bumped www.videomail.io with these changes - if you do not mind to check again, that would be very much appreciated.

**Comment by bfred-it** [comment]
The video width is 0
<img width="425" alt="screen shot 2016-04-20 at 12 23 37" src="https://cloud.githubusercontent.com/assets/1402241/14664191/722df02c-067d-11e6-9c56-7091cef4612e.png"> 

Once I set that to something else the video appears, but for some reason the module is not running because the symbols are not there and the video plays fullscreen. Also you're missing the CSS to hide the play button https://github.com/bfred-it/iphone-inline-video#usage

**Comment by binarykitchen** [comment]
Right, I can reproduce all the above with Valence now (but have added the missing CSS).

So, I have really no idea why width is set to 0. In the Videomail-Client code I set the width and height of the video dom element before the `makeVideoPlayableInline()` call. Is that good or should I set width/height after that call?

See from https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/replay.js#L86

**Comment by bfred-it** [comment]
Video size shouldn't affect the module. You just need to make sure that the `src` or `currentSrc` properties are set when you call that function.

**Comment by binarykitchen** [comment]
@bfred-it ah, finally got it. the height was wrongly calculated before. works well on iphones now :)

but why does the video play full-screen and not inline? any ideas why?

**Comment by bfred-it** [comment]
https://github.com/bfred-it/iphone-inline-video/issues/16#issuecomment-208790152

You're not calling the function. I called it on the video and it works on your website. The only thing is that you can't use the browser's play/pause buttons: https://github.com/bfred-it/iphone-inline-video/issues/16#issuecomment-212265170
