### ISSUE TITLE
Add an option to debug it on Non-Safari browsers

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#17]
Since I develop on Linux and do not have Safari, is there a way to force makeVideoPlayableInline to run it even on Firefox or so? So that I can debug properly?

**Comment by bfred-it** [comment]
It seems to work correctly on Firefox already. To debug it properly you need Safari and an iPhone, there's no other way around it. Perhaps use Browserstack or something like this: https://developer.mozilla.org/en-US/docs/Tools/Valence

**Comment by binarykitchen** [comment]
Ah, Valence is wonderful. I can debug now. Many thanks!
