### ISSUE TITLE
Looping video on mobile

### ISSUE THREAD

**Issue by haveanicedavid** [bfred-it/iphone-inline-video#19]
Is is possible to make autoplay video loop on mobile? 

I'm using a `<video>` tag with autoplay & loop enabled. Works fine on desktop and the initial load on mobile, but won't repeat / loop.

**Comment by haveanicedavid** [comment]
Ahh found this in a previous issue #14 

Closing

**Comment by bfred-it** [comment]
FYI this feature was added in 1.5.0
