### ISSUE TITLE
Possible to do seek?

### ISSUE THREAD

**Issue by hongxiangrong** [bfred-it/iphone-inline-video#2]
First of all, it works great! Audio could shift playback a little forward to make a tighter sync, but otherwise, it's great! Wondering whether you can implement currentTime seek. I know the demo code has comments that the user cannot set this. Is there a way round to do this?

**Comment by bfred-it** [comment]
There is, I don't have time right now but you can probably just add

```
	proxyProperty(video, 'currentTime', player);
```
In the `overloadAPI` function: https://github.com/bfred-it/iphone-inline-video/blob/gh-pages/index.js#L116-L118

**Comment by bfred-it** [comment]
Can you try this branch? It seems to be working in my tests

**Comment by hongxiangrong** [comment]
Tried dist/iphone-inline-video.browser.js of that branch. doesn't seem to work on the iphone.

**Comment by bfred-it** [comment]
What iPhone and iOS did you test it on?

**Comment by hongxiangrong** [comment]
iPhone 5 iOS 9.3.1

**Comment by bfred-it** [comment]
How are you testing it?

I just added a seeking button in the `index.html` demo file. Start playing the video first and then press that button. It seeks by running `video.currentTime = <random time in seconds>`. Can you try it?

Download it from here: https://github.com/bfred-it/iphone-inline-video/tree/seeking-test

**Comment by hongxiangrong** [comment]
i was manually including dist/iphone-inline-video.browser.js
I just tested it using your suggested way. It works great! Thanks so much. This is the best result from all the other inline attempts made on the iphone.

**Comment by hongxiangrong** [comment]
Hi all, these HTML5 player control implementation works well together. We've tested the seekbar and it works great for progress indication and seeking.
https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Video_player_styling_basics

**Comment by bfred-it** [comment]
I merged this change into 1.4.0 and it's now on npm
