### ISSUE TITLE
Detect webview

### ISSUE THREAD

**Issue by bouniflax** [bfred-it/iphone-inline-video#21]
When it runs inside a webview with webview.allowsInlineMediaPlayback = YES the video runs with the plugin but there is no need to (I've then experience some delays in events like play); it would be good if your plugin could detect this case and not fire.

Anyway great work your plugin is amazing.

**Comment by bfred-it** [comment]
Unfortunately there's no way to detect that until the video actually goes fullscreen. That could be somewhat prevented but it either doesn't look good or is crashy. I'll leave it open but I don't think it's possible to detect properly.

**Comment by bouniflax** [comment]
Ok thanks, If I find a way I will post it here

Le lundi 18 avril 2016, Federico Brigante <notifications@github.com> a
écrit :

**Comment by bfred-it** [comment]
I looked into it again and, no: https://github.com/Modernizr/Modernizr/issues/1498#issuecomment-214218215

I was hoping to make my module _lazy_ (which is: initialized only when needed) by waiting for the video to go fullscreen before activating, but it's not _good enough._ You could use something like this to make it lazy:

```js
video.addEventListener('webkitbeginfullscreen', function() {
        video.webkitExitFullscreen();
        makeVideoPlayableInline(video);
        video.play(); // this might not work without another user touch
});
```
