### ISSUE TITLE
ended event not firing on mobile.

### ISSUE THREAD

**Issue by jimmymain** [bfred-it/iphone-inline-video#23]
Given the following code:

- The video loads when the load method is called. (I am not using autostart or loop).
- The 'data is loaded' is written once to the notification pane.
- The video starts playing on iphone / desktop browser but, **not on ipad**.
- No **ended** event is ever triggered by the video element on the phone or ipad, but in a desktop browser it is triggered.

_Is there another method of detecting the video has ended._
_Is it possible to get the player to work on an ipad?_
any pointers would be appreciated, I am happy to try and help get it working.

```
jQuery(document).ready(function() {

    console.log('loading video tags');

    var count = 1;
    var video = jQuery('#bannerVideo').get(0);
    makeVideoPlayableInline(video, false);
    video.addEventListener('ended', function() {
        jQuery('div.notify').html('video has ended');
    });
    video.addEventListener('loadeddata', function() {
        jQuery('div.notify').html('data is loaded' + count++);
        window.setTimeout(function() { video.play(); }, 3000);
    });
    video.load();

});
```

The html looks like this

```
        <div class="video-container">
                <div class="notify">notify</div>
                <video width="100%" preload="metadata" id="bannerVideo">
                <source
                    src="wp-content/uploads/2016/04/video.mp4"
                    type="video/mp4"
                    alt="">
                </video>
        </div>
```

**Comment by bfred-it** [comment]
If you want to enable it on the iPad: https://github.com/bfred-it/iphone-inline-video/pull/22#issuecomment-211822532

---

Normally the `ended` event should fire (https://github.com/bfred-it/iphone-inline-video/blob/gh-pages/index.js#L87). When the video ends, could you verify that the `ended` property is true on the video with Safari's remote debugger? (e.g. `video.ended`) If not, verify that the `.currentTime` matches `.duration`. It sounds strange that the iPad isn't triggering the event, considering that the module doesn't affect it at all.

**Comment by jimmymain** [comment]
I am on windows, so that is tricky.
Will it help if you can browse to our [test site](http://palantir.northeurope.cloudapp.azure.com/)

You can see a div with the status text on it, which changes under chrome and firefox, but not iphone or ipad.

The video there is now working rather nicely on iphone and ipad so thanks very much for that.
All that remains is that I want to restart the video when it finishes, but alas that event is not triggering on the pad or phone.

Thanks!

**Comment by jimmymain** [comment]
I added the following code:
```
    window.setInterval(function() {
        jQuery('div.notify').html(`end: ${video.ended}, ${video.currentTime}, ${video.duration}`);
    }, 1000);
```

the current time and duration are logged correctly, but the numbers are not identical on the ipad and iphone. Looks like a rounding error.

```
desktop:end: true, 9.357641, 9.357641
iphone i get: end: false, 9.3566666, 9.35666666666666667.
```

If you are measuring the time, I think you might need to use an **epsilon comparison?**

**Comment by jimmymain** [comment]
I have reencoded the video and the end event is now triggering. Judging by what I have been reading video on mobile is a minefield.

Not sure if you want to chalk this up to a glitch. Perhaps you have some idea why the duration was a rounding error higher than the current time.

**Comment by bfred-it** [comment]
I'll look into it, possibly the rounding issue is happening inside the `Math.min` function. If you still have the old video and it doesn't take long, could you test the version in the `loop-support` branch? It has slightly different code

**Comment by bfred-it** [comment]
If that doesn't work, would you mind sending me the video? There could be issues in setting the time to that specific value (i.e. the browser resets 9.35666666667 to 9.3566666 and the only solution is to calculate `.ended autonomously, but it might not show the very last frame in some cases)

**Comment by bfred-it** [comment]
I published v1.5.0, can you verify that it works with your old video

**Comment by bfred-it** [comment]
I'd love to get this fixed—before I or anyone else bumps into this

**Comment by bfred-it** [comment]
Eventually I did bump into this with a video having a length of `2.5025025025025025`
