### ISSUE TITLE
Running inside ionic 2 framework

### ISSUE THREAD

**Issue by vardas-bill** [bfred-it/iphone-inline-video#24]
I have been trying to use iphone-inline-video in my ionic 2 app but without success. The video still opens full screen. Are you aware of anyone using it successfully in ionic 2?

**Comment by bfred-it** [comment]
There seems to be an official way to make it work in Ionic, but it doesn't work yet: https://github.com/driftyco/ionic-view-issues/issues/126

I can't debug your application, but I'd make sure that you call the `makeVideoPlayableInline` function on a video element that is ready to use, which means it already has the correct `src` applied. If you are using it with browserify or similar, I'd just edit the `iphone-inline-video.common-js.js` file to show all `console.log()` statements and help you debug it better.
