### ISSUE TITLE
"ReferenceError: Can't find variable: Symbol"

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#26]
Happened on videomail.io with your latest version.

Useragent was `Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.858 Mobile Safari/537.35+`

And the matching code line was
`var _Symbol = void 0 === Symbol ? function(description) {`

In case if you want to debut, it is there
`https://videomail.io/js/main-a35a84d532.min.js:11704:undefined`

**Comment by bfred-it** [comment]
Ah rookie mistake. I'll try to fix this soon

**Comment by bfred-it** [comment]
Thanks for the report! It should be fixed in 1.6.4

**Comment by binarykitchen** [comment]
no worries, can happen. thanks for the quick fix!

but could you add some unit tests so that they won't happen again in the future?

**Comment by bfred-it** [comment]
Only when I'll _find time_ to do it 😅
