### ISSUE TITLE
Demos not working properly

### ISSUE THREAD

**Issue by bramus** [bfred-it/iphone-inline-video#27]
I noticed that the demos aren't working properly due to the video being used (`https://media.w3.org/2010/05/sintel/trailer.mp4`) not loading correctly _(ranging from timeout, to ssl error, to ...)_

I'd recommend including a (small) sample MP4 file into this repo, and referring to it using a service such as https://rawgit.com/

**Comment by bfred-it** [comment]
Good idea, any suggestions for a short video matching with the MIT license?

**Comment by bramus** [comment]
[Big Buck Bunny](http://www.bigbuckbunny.org) is a commonly used example as it's licensed under a Creative Commons Attribution 3.0 license. You can find many snippets on the web, such as over at https://github.com/bower-media-samples (even those files could be loaded straight over rawgit).
