### ISSUE TITLE
Use with Videogular

### ISSUE THREAD

**Issue by frey1esm** [bfred-it/iphone-inline-video#3]
Will this work with [videogular](https://github.com/videogular/videogular) and particularly multiple indexed players on a single page?

This is brilliant BTW!

**Comment by bfred-it** [comment]
Sort of, it can probably play the video, but [no seeking yet](https://github.com/bfred-it/iphone-inline-video/issues/2)

**Comment by bfred-it** [comment]
Can you test this version and let me know it works?

https://github.com/bfred-it/iphone-inline-video/issues/2#issuecomment-204944568

**Comment by frey1esm** [comment]
I was actually able to make the videogular script play iphone video inline without your script.

**Comment by bfred-it** [comment]
Cool, so we can close this =)
