### ISSUE TITLE
The Video Pauses Approximately Every Second

### ISSUE THREAD

**Issue by arunshan** [bfred-it/iphone-inline-video#35]
@bfred-it For some reason the video pauses every second and resumes playing triggering the timeupdate event every 200ms. How can we make the video play smoothly without pausing?

**Comment by bfred-it** [comment]
You might want to wait for the `canplaythrough` event before playing. Also make sure that the server serves the right cache headers because otherwise the video and audio will trigger two separate requests for the same file. Let me know how it goes

**Comment by arunshan** [comment]
1. Yes I am using the video with audio.
2. Could you explain more on cache headers? 
3. This is the example video that we are working on. 
https://fuisz-experience-staging.herokuapp.com/572de08fb1f04b2549417f44/ios.html
You can test it on iPhone user agent in chrome. I added `canplaythrough` but I still see that
the video is choppy.

**Comment by bfred-it** [comment]
2: http://dev.mobify.com/blog/beginners-guide-to-http-cache-headers/
3: You can't test it on Chrome, it works on iPhone only, not Chrome

**Comment by arunshan** [comment]
@bfred-it Thank you for your help.
