### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by bfred-it** [bfred-it/iphone-inline-video#43]
Personal wishlist/notes
- play audio via AudioContext to add `volume`/`mute` support and only require the first touch to play: https://github.com/bfred-it/iphone-inline-video/issues/41#issuecomment-219610729
- return a Promise on `.play()`: https://developers.google.com/web/updates/2016/03/play-returns-promise
- allow toggling between muted and unmuted
  - allow setting of mute via `mute` attribute instead of parameter
- wait for the [resource selection algorithm](https://www.w3.org/TR/html5/embedded-content-0.html#concept-media-load-algorithm) if `<source>` is used and `.currentSrc` is empty (i.e. `.networkState === .NETWORK_NO_SOURCE || .NETWORK_EMPTY`)
  - improve and test support for video `src` update (i.e. verify the video state and the audio track loading)
- allow complete enabling and disabling of IIV (would be nice for https://github.com/bfred-it/iphone-inline-video/issues/33)
  - extend the prototype automatically and enable it on request, this prevents late activation errors
  - allow enabling via webkit-playsinline
    - add automatic mode (`enableInlineVideo(/*no params*/)`)
- make sure that playing multiple videos with audio behaves as expected (one stops, the other plays)
- look into automatically stopping the audio when the user switches tab
- handle airplay somehow

**Comment by jeroentradecast** [comment]
Wouldn't "play audio via AudioContext to allow volume change" be unnecessary? Afaik no mobile devices have a volume control for native html5 video elements. Iirc ios doesn't even allow volume control on native html5 video, setting a value between 0 and 1 is ignored.

**Comment by bfred-it** [comment]
Test

```js
whatever(); code();
```
