### ISSUE TITLE
Not working on Ipad?

### ISSUE THREAD

**Issue by 0xsven** [bfred-it/iphone-inline-video#48]
Is there a reason why it doesn't work on my ipad?

I am on iOS 9.2.1

**Comment by bfred-it** [comment]
What are you trying to do on the iPad? It's disabled by default because the iPad plays videos inline natively

**Comment by 0xsven** [comment]
Thank's for the info.

Do you know if I have to do something to make them autoplay? I have put the attribute on the video element but it doesn't autoplay on iPad.

**Comment by bfred-it** [comment]
There is a third parameter that when set to `false` IIV will be run in all browsers, not just iPhone and iPod. 

This is what you're looking for to enable silent auto playing videos on the iPad:

```js
if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
    makeVideoPlayableInline(video, false /* hasAudio */, false /* false = run everywhere */);
}
```

**Comment by bfred-it** [comment]
In the v2 beta I simplified the usage on iPad. Can you try it and let me know how it goes?

- [v2 changelog](https://github.com/bfred-it/iphone-inline-video/blob/2.0/CHANGELOG.md)
- [v2 usage documentation](https://github.com/bfred-it/iphone-inline-video/tree/2.0#install)
- [iphone-inline-video.js](https://github.com/bfred-it/iphone-inline-video/tree/2.0/dist)
- If you use npm, you can install the beta with: `npm install iphone-inline-video@next`

**Comment by bfred-it** [comment]
v2.0.0 has been published :)

Now you can use the `iPad` option:

```js
enableInlineVideo(video, {
    iPad: true
});
```
