### ISSUE TITLE
Official support coming in Safari 10

### ISSUE THREAD

**Issue by slavanga** [bfred-it/iphone-inline-video#51]
Safari 10 will support inline playback and autoplay of videos without audio tracks or with disabled audio tracks. Ideally this script should not run if native support is detected.

https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-DontLinkElementID_12

**Comment by bfred-it** [comment]
Cool stuff! I'll add a <iOS 10 check
