### ISSUE TITLE
Subtitle is disappear after display at the same time

### ISSUE THREAD

**Issue by bchieu** [bfred-it/iphone-inline-video#54]
when I add track into video, this not work correctly

**Comment by bfred-it** [comment]
Show me your code

**Comment by bchieu** [comment]
thanks for reply, i don't have demo on website :(, this is my code, 

playvideo(){
     var vid = document.getElementById("vid");
     vid.src = "file:///Users/binh/Library/Developer/CoreSimulator/Devices/DABD3377-7776-49A0-A541-F46B1CDC30A5/data/Documents/Video/abc.mp4";
    makeVideoPlayableInline(vid); 
     vid.play();
},

<video width="100%" height="200" id= "vid" controls webkit-playsinline className="playr_video">
	   			 <source type="video/mp4" src=abc.mp4" />
		        <track id="entrack" src="abc.srt" kind="subtitles"  srcLang="en-us" label="English" type="text/x-srt" default/>		      			 		  				    
</video>


the video play ok, but the subtitle have issues, it's disappear too fast, when i try it when use native video the subtitle work fine
I don't know how to solve it :(

**Comment by bfred-it** [comment]
I tested it here and it seems to work correctly: http://codepen.io/anon/pen/LZxvPL

Without a working demo I don't know why it doesn't work for you.
