### ISSUE TITLE
Support changing the src

### ISSUE THREAD

**Issue by bfred-it** [bfred-it/iphone-inline-video#6]
Changing `src` isn't supported yet, so you can't play videos back-to-back yet ([already tried](https://github.com/bfred-it/iphone-inline-video/commit/01ba322b5da0a09afda747834160cd11b84cf145), not as easy)

**Comment by mrlrc** [comment]
Appreciate your work on this, in my implementation, I would like to have the src to be passed into the page by query string (video only, no audio), will it work?

**Comment by bfred-it** [comment]
You can already do that if you can "enable" the `video` element after setting the src, like so:

```js
var v = document.createElement('video');
v.src = 'data:video/mp4;base64,....'; // I assume you meant this
makeVideoPlayableInline(v);
document.body.appendChild(v);
```

The only issue is that if you want to change video, you need a new video element (basically run that whole code above every time).

Also I suggest working with blobs where possible because base64 is quite heavy in memory and leads to browser crashes.

**Comment by bfred-it** [comment]
This feature has been added now =)
