### ISSUE TITLE
iPad in-line video autoplay

### ISSUE THREAD

**Issue by AlexB1337** [bfred-it/iphone-inline-video#60]
Dear Federico,
thank you for the code. It works perfectly on iPhone. Could you please show a working example of init code for iPad, using this:
```
if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
    makeVideoPlayableInline(video, false /* hasAudio */, false /* false = run everywhere */);
}
```
I dont have any access to iPad at the moment and cant test the code, so would appreciate your help. Thanks in advance!

**Comment by bfred-it** [comment]
I don't have that specifically but you can try this URL, it's enabled everywhere (not just iPhone iPod and iPad), meaning that the third parameter is `false`

http://bfred-it.github.io/iphone-inline-video/demo/?enabled=true
