### ISSUE TITLE
CSS to hide play buttons

### ISSUE THREAD

**Issue by joeyhoer** [bfred-it/iphone-inline-video#62]
In commit https://github.com/bfred-it/iphone-inline-video/commit/a4ddfc874370c0b0ab1b0ba3d06296695070ad61:

```
video::-webkit-media-controls-start-playback-button {
    display:none;
}
```

was changed to:

```
.IIV::-webkit-media-controls-play-button,
.IIV::-webkit-media-controls-start-playback-button {
    opacity: 0;
    pointer-events: none;
    width: 5px;
}
```

and the comment was updated to read "the native play buttons will still trigger the fullscreen, so it's best to hide them (without breaking the video `controls`)".

I'm wondering if the `5px` is necessary. I'm not seeing any issue in removing it, and `opacity` + `pointer-events` seems to be sufficient. I also don't see an issue with `display: none`, but it would be helpful to understand the specific purpose and what it affects.

**Comment by bfred-it** [comment]
The previous code hid the big play button; the new code also hides the play button in the `controls` bar. Those three properties are necessary to hide it without ruining the style of the `controls` bar
