### ISSUE TITLE
Safari crashes when trying to play

### ISSUE THREAD

**Issue by maximilliangeorge** [bfred-it/iphone-inline-video#67]
When i try to play a video, via an event handler or via timeout the website crashes (A problem occurred with this web page, so it was reloaded). It then refreshes the page (restoring the pre-crash state, i think). The video is playing fine on reload, but i'd prefer it not to crash.

**Comment by bfred-it** [comment]
Show an example, the device you're testing it on and it's iOS version. Does the demo work on it? It's possible that you're already doing too much on the page and IIV is the last drop.

**Comment by maximilliangeorge** [comment]
That was indeed the case. I tested using other media and it still crashed. I was pushing the browser pretty hard as it was. 

Sorry for the false alarm!
