### ISSUE TITLE
Multiple videos aren't playing

### ISSUE THREAD

**Issue by modermo** [bfred-it/iphone-inline-video#69]
I have a collection of three videos on one page. The issues I'm having is that only one of them (the first of the three) is autoplaying. I'm using standard code here:

```
<script>
  $('video').get().forEach(makeVideoPlayableInline);
</script>
```

**Comment by bfred-it** [comment]
Try: 

```js
$('video').each(function() {
makeVideoPlayableInline(this, false);
});
```

**Comment by adamjw3** [comment]
I have multiple videos working on the same page but only on iphone 5, iphone 6 and up it just stops the site, doesn't move forward with the js. Can this be fixed?

**Comment by adamjw3** [comment]
Just to add to this my iphone 5 is ios 9.3.5 and iphone 6 and 7 are the latest version 10.

**Comment by bfred-it** [comment]
IIV is disabled automatically on iOS 10

**Comment by adamjw3** [comment]
Anyway of not disabling it? your implementation for ios 9 is better than apples it would seem. just wondering if that would solve the issue
