### ISSUE TITLE
chrome mobile on iOS 10 not allowing inline

### ISSUE THREAD

**Issue by uotw** [bfred-it/iphone-inline-video#73]
Hello,  I'm using the most recent version of iphone-inline-video on iOS10 with the following code:

```
$(document).ready(function() {
        $('video').each(function (index, value) { 
             makeVideoPlayableInline(document.getElementById($(this).attr('id')), false,false);
              id=$('video').first().attr('id');
              document.getElementById(id).play();
        });
});
...

document.getElementById(id).play(); //TO PLAY, SURROUNDED BY CODE
```

The videos do not play unless clicked twice, despite my call above.  When clicked twice they go full screen.  Once I exit full screen they do play programmatically but the play button remains over top.

**Comment by uotw** [comment]
I was able to get this working by hiding the native play button using CSS and setting autoplay to true when mobile chrome is detected.

**Comment by bfred-it** [comment]
Do you have the `playsinline` and `mute` attributes? On iOS 10, iphone-inline-video is disabled automatically because this functionality is supported natively with that attribute.

**Comment by uotw** [comment]
Yes, I do have both these attributes set.

**Comment by bfred-it** [comment]
Technically it should be supported so IIV is disabled there. Try StackOverflow since this is an issue with iOS 10 Chrome rather than IIV. Let me know if you find anything

**Comment by giannoudak** [comment]
Hello all!
@uotw  i face the same issue on Chrome and Firefox on iOS10. I have to tap to start video playback. When i tap it goes fullscreen and on exit it plays inline.

**Comment by bfred-it** [comment]
This should look green in all iOS 10 browsers, does it work? http://codepen.io/anon/pen/xEdwop

Does this work in Chrome/iOS? https://bfred-it.github.io/iphone-inline-video/?enabled=true

**Comment by giannoudak** [comment]
Hi bfred-it!
1. this looks green only on safari. on chrome and firefox is this is red
2. Actually No. The big play button is there. The video goes fullscreen after click to play and when on fullscreen exit it returns playing inline

**Comment by bfred-it** [comment]
0. So the native inline playback functionality is not enabled in Chrome and Firefox; therefore IIV would have to be enabled there.
0. Can you try again? The demo was broken

**Comment by giannoudak** [comment]
i can see the following:
the second video never starts playback
the first requires has a large delay to start after i click on Play/Pause button

**Comment by bfred-it** [comment]
It sounds like this is happening because they broke the manual `video.load()`. So the first video is loaded after the first tap (instead of being preloaded) and the second video never autoplays because there's no tap and therefore no `load()` call.

No solution, we just have to wait for the browsers to enable the native playback, also because third-party browsers are not debuggable as far as I know, so I can't even know what is happening exactly.

**Comment by uotw** [comment]
@giannoudak Here's my working solution.  http://codepen.io/utnuc/pen/mAmEyp

**Comment by bfred-it** [comment]
I don't think that works, since IIV is not enabled at all on iOS and you're not forcing it with the third parameter

**Comment by uotw** [comment]
Both links seem to work here on Chrome, iPhone 6s, iOS10.  Stops working when I remove iphone-inline-video.js.

**Comment by bfred-it** [comment]
What's the output of this in Chrome/iOS? http://codepen.io/anon/pen/GjmqxX?editors=1111
You should see a popup

**Comment by uotw** [comment]
true,,true

**Comment by bfred-it** [comment]
Thanks, appreciated. It looks like [Safari 10 did not enable the CSS grid,](http://caniuse.com/#feat=css-grid) which is what I was using to detect iOS 10, and therefore IIV still runs on iOS 10.

Also for some reason IIV's autoplay support isn't working, but `.play()` is. So try these two solutions:

Normal play: http://codepen.io/anon/pen/ALRXwO
Autoplay: http://codepen.io/anon/pen/kkyXVk

**Comment by uotw** [comment]
On Chrome/iOS, the first link does nothing, blank page.  Second link is blank until I hit play, then it plays the video inline w/ audio.

**Comment by jakelewis3d** [comment]
_"It looks like Safari 10 did not enable the CSS grid, which is what I was using to detect iOS 10, and therefore IIV still runs on iOS 10."_

So we should change the test:
void 0 === document.head.style.grid
to something that detects iOS 10?

**Comment by bfred-it** [comment]
There's a media query to detect this behavior specifically, but that doesn't fix the issue, since Chrome/iOS 10 doesn't support IIV natively anyway. The fix is in @uotw's comments but I have no time to implement either at the moment.

**Comment by bfred-it** [comment]
Chrome/iOS 10 now supports `playsinline` natively (this is [green](http://codepen.io/anon/pen/xEdwop))

Demo: https://vid.me/CFDy

Firefox on the other hand still doesn't fully support autoplaying video inline on iOS 10, even with IIV. I'm creating a new issue specific to that.

**Comment by eysi09** [comment]
Actually the is still an issue. The link in your comment above is red on my browser (latest Chrome) and IIV videos are not playing on Chrome iOS (iPhone 6s, iOS 10+).

**Comment by bfred-it** [comment]
![img_6251](https://cloud.githubusercontent.com/assets/1402241/21012171/19bbc734-bd98-11e6-9065-c5a77a93bbd2.PNG)
![img_6252](https://cloud.githubusercontent.com/assets/1402241/21012170/19b5c7a8-bd98-11e6-9826-63c8d480f3ec.PNG)
![img_6253](https://cloud.githubusercontent.com/assets/1402241/21012359/f46ca97a-bd98-11e6-9380-8b4b2b9d81b4.PNG)


I don't know what to tell you. Works for me on iOS 10.1. The first demo doesn't work anywhere, it seems, because of connection issues, but the three.js muted autopley demo works natively, without IIV

**Comment by eysi09** [comment]
Ah my bad. Turns out I wasn't on the latest Chrome version on my iPhone. Sorry for the trouble and thanks for the quick reply.

**Comment by bfred-it** [comment]
Update: IIV works 100% on Firefox 5.3 (2) on iOS 10.2: https://github.com/bfred-it/iphone-inline-video/issues/84

I did nothing, but they probably fixed something :)
