### ISSUE TITLE
On autoplay iPad iOS9 does not dispatch initial 'play' or 'playing' event (does do this on iPhone iOS9)

### ISSUE THREAD

**Issue by fox94610** [bfred-it/iphone-inline-video#75]
Used below method to kick off autoplay on iPad:
makeVideoPlayableInline(videoElement, false/* hasAudio */, false/* false = run everywhere */);
Works great but I would like to detect 'play' or 'playing' event. Is there a way to do this? If not is it possible to patch?

iPhone logging...
http://foxflare.com/mobileEvent/ss1.png

Same page on iPad...
http://foxflare.com/mobileEvent/ss2.png

**Comment by bfred-it** [comment]
That's strange, they shouldn't behave differently. I'll look into this

**Comment by bfred-it** [comment]
I can't test on the iPad right now, but can you open this URL there to see if the events are fired? It has the same logging http://bfred-it.github.io/iphone-inline-video/?enabled=true

**Comment by fox94610** [comment]
I checked it out, you definitely have the play and playing event firing on your page. I guess it's not a bug. Something is weird with my JS writing everything to the page implementation. Maybe some race condition in there somehow messing up the initial play and playing events.

**Comment by bfred-it** [comment]
Thanks for reporting!

**Comment by bfred-it** [comment]
In the v2 beta I simplified the usage on iPad. Can you try it and let me know how it goes?

- [v2 changelog](https://github.com/bfred-it/iphone-inline-video/blob/2.0/CHANGELOG.md)
- [v2 usage documentation](https://github.com/bfred-it/iphone-inline-video/tree/2.0#install)
- [iphone-inline-video.js](https://github.com/bfred-it/iphone-inline-video/tree/2.0/dist)
- If you use npm, you can install the beta with: `npm install iphone-inline-video@next`

**Comment by bfred-it** [comment]
v2.0.0 has been published :)

Now you can use the `iPad` option:

```js
enableInlineVideo(video, {
    iPad: true
});
```
