### ISSUE TITLE
Does this work for iOS < 8?

### ISSUE THREAD

**Issue by lalarsson** [bfred-it/iphone-inline-video#76]
Hi!

Thanks for an awesome lib! I was wondering how the heck I was supposed to solve this problem within a few days and then stumbled upon this awesomeness! Thanks!

While checking out my inlined video at Browserstack I noticed that it autoplays on iOS10-8 but not below iOS 8. I'd very much like it to work as far back as possible, but I don't know if it's an error on my end or if the lib doesn't support inlined autoplay that far back.

So my question is: how far back does this lib work?

**Comment by bfred-it** [comment]
It works in iOS 8 and iOS 9. iOS 7 I think doesn't support the mechanism I'm using and also it errors because IIV tries to override video.play and fails.
