### ISSUE TITLE
Autoplay doesn't work on 4 inch devices

### ISSUE THREAD

**Issue by SG5** [bfred-it/iphone-inline-video#79]
Demo `https://bfred-it.github.io/iphone-inline-video/demo/` (and my local video) doesn't start play at iphone 5, 5s, SE with IOS 10

**Comment by bfred-it** [comment]
What iOS version and what browser?

**Comment by SG5** [comment]
iOS 10 with safari

**Comment by bfred-it** [comment]
iphone-inline-video is only for iOS 8 and 9 and it's automatically disabled on iOS 10.

iOS 10 Safari supports inline playback natively with the `playsinline` attribute: https://github.com/bfred-it/iphone-inline-video#notes-about-ios-10

If it doesn't work there's probably a network error and either way unrelated to iphone-inline-video. Does this video load for you? https://rawgit.com/bower-media-samples/big-buck-bunny-480p-30s/master/video.mp4

**Comment by SG5** [comment]
On all 4+ inch devices with ios 10 autoplay work fine

**Comment by bfred-it** [comment]
It's probably a coincidence, there doesn't seem to be anything regarding device compatibility in the official announcement: https://webkit.org/blog/6784/new-video-policies-for-ios/

Is this green on those devices? https://codepen.io/anon/pen/xEdwop
