### ISSUE TITLE
Small issue with loading

### ISSUE THREAD

**Issue by maltejanosch** [bfred-it/iphone-inline-video#80]
I have everything set up and the video does play inline. 
The problem, that I have now, is that the audio plays fine, but the video isn't running smooth. 
It looks like it's trying to buffer, even though the video is fully loaded.

Example: [https://www.ohraacties.nl/ohra2/welkomstvideo/test.html]

Has anyone encountered this issue before, or has an idea where the problem could be?

**Comment by hugohow** [comment]
I have the same problem there : https://enigmatic-reaches-68782.herokuapp.com

**Comment by maltejanosch** [comment]
I found a little Hack solution to fix the problem.

I just disabled the "buffer circle" animation and it fixed the issue. This isn't completely fixing the issue, but at least it is working for me now!

**Comment by bfred-it** [comment]
Thanks for reporting back! I've been quite busy to investigate this issue further 😅

**Comment by maltejanosch** [comment]
No Problem, have you seen the issue before? 
I am not sure if the problem is connected to my code or to yours. But because turning off the buffer wheel fixed the issue for me, I believe it was my code that had a problem!

**Comment by bfred-it** [comment]
No but IIV [doesn't cover the entire API](https://github.com/bfred-it/iphone-inline-video/issues/8) that VideoJS might depend on to work correctly.
