### ISSUE TITLE
It's still play fullscreen on your demos

### ISSUE THREAD

**Issue by ethancfchen** [bfred-it/iphone-inline-video#82]
When I click the play button on the bottom, seem that it still play fullscreen.
Device: iPhone 6 plus
OS: iOS 10.0.2

**Comment by bfred-it** [comment]
hah, that's ridiculous, isn't it?! 😅

Thanks! I fixed it, I was using the old apparently-no-longer-supported `webkit-playsinline` attribute instead of `playsinline`
