### ISSUE TITLE
Significant choppiness in iOS Facebook App browser (sometimes on Safari also)

### ISSUE THREAD

**Issue by Meyenehi** [bfred-it/iphone-inline-video#86]
I have a use case where the videos that use this tech will mostly be accessed through Facebook. However, in the Facebook App browser we're experiencing significant video lag, to the point where we receive one still image every 5 seconds. Tested on iOS 8, 9 and 10. Hoping there's a solution to this.

**Comment by bfred-it** [comment]
Wait, you said it's choppy on iOS 10? IIV doesn't run at all on iOS 10
