### ISSUE TITLE
Object.defineProperty crash on iOS7.

### ISSUE THREAD

**Issue by phyllisstein** [bfred-it/iphone-inline-video#87]
Hey there! I noticed that attempting to use this polyfill on iOS7 causes a crash on `proxy-property:14`. It appears that the attributes of the `video` element aren't configurable, so trying to call `Object.defineProperty` on them fails:

<img width="566" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/2207980/20234948/4eb3923c-a853-11e6-9abb-accdb3951444.png">

Not sure if iOS7 is meant to be officially supported---it's not mentioned in the README---but it'd be great if you could suggest a way around this. I'm reluctant to submit a PR since I have no good sense of the best way to handle the error, but I'm certainly open to suggestions.

**Comment by bfred-it** [comment]
There's a iOS 8-9 badge below the title. Unfortunately the behavior IIV depends on is not available on iOS 7, so there's no way around it

**Comment by phyllisstein** [comment]
Sure, of course. My thinking was less "this library should work on iOS <8" than "maybe this library could degrade more gracefully on iOS <8." Turned out that invoking it wrapped in a `try...catch` block was sufficient, though 😃 . Thanks for the response!

**Comment by bfred-it** [comment]
That's a good point. I'll detect iOS 7

**Comment by bfred-it** [comment]
Can you try version 1.9.5-0? I don't have an iOS 7 device to test this.

That version is currently installable with `npm install iphone-inline-video@next` or by downloading the latest file in `dist` on the repo

**Comment by phyllisstein** [comment]
Beautiful! That seems to resolve the crash on iOS7. I really appreciate your looking into this; thanks for taking the time.

**Comment by bfred-it** [comment]
Thanks for reporting back! It's been released as 1.9.5
