### ISSUE TITLE
sound issue on ios 10 (iphone6)

### ISSUE THREAD

**Issue by ofirrifo** [bfred-it/iphone-inline-video#88]
first thanks for great package.

this is the code I'm using
                    var video = document.querySelector('video');
                    makeVideoPlayableInline(video, true);
                    video.play();
to initiate video play.

I'm using video API timeupdate 

 videoElement.on('timeupdate', function (e, b) {
   // when I set sound to  true in method makeVideoPlayableInline I never reach to here
}

this is the exception I get:
iphoneInlineModule.js:90 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

please advise.

**Comment by bfred-it** [comment]
iOS 10 does not need IIV

What browser are you using?

**Comment by ofirrifo** [comment]
👍 after I  using <video src=... instead of <source>
it work.
thanks
