### ISSUE TITLE
iOS 10 WKwebview

### ISSUE THREAD

**Issue by erikandershed** [bfred-it/iphone-inline-video#89]
Will it work in a WKwebview on ios10. Because I can't get the playinline or autoplay to work. Even if it work in safari it will not work in WKwebview. 

Please help.

**Comment by bfred-it** [comment]
What color is this in that view? https://codepen.io/anon/pen/xEdwop

If it's green, then IIV is disabled and `playsinline` should work natively.

If it's red, either look into how to enable `playsinline` in your WKWebView or verify that the video element has an `IIV` class. If not, you're probably not running IIV correctly.

**Comment by erikandershed** [comment]
sweet function! It's red for me. How is do I enable the playinline in my WKWebView?

**Comment by bfred-it** [comment]
Google

**Comment by erikandershed** [comment]
I have google it like for ever.. there is no help. Do you know anyone how can help me?

**Comment by bfred-it** [comment]
StackOverflow

**Comment by Reon90** [comment]
@erikandershed 
<preference name="AllowInlineMediaPlayback" value="true" />
