### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by bknill** [bfred-it/iphone-inline-video#9]
I'm getting this error on iPhone 5, iOS 9.3 

> TypeError: Attempted to assign to readonly property.

Here is my video constructor
```js
if(!video){
            video = document.createElement( 'video' );
            //video.width = 2048;
           // video.height = 1024;
            video.autoplay = true;
            video.loop = true;
            video.crossOrigin = '';
            video.preload = 'auto';
            video.setAttribute('webkit-playsinline', 'webkit-playsinline');


        }

        video.src = cdnPrefix + "/"+ sceneObject.video;

        const videoPlayer = document.querySelector('video');
        makeVideoPlayableInline(videoPlayer);
```

If I remove 'use Strict' I get 

> TypeError: null is not an object (evaluating 'n[a]={}')

Any ideas what that could be?

**Comment by bfred-it** [comment]
`document.querySelector('video')` looks for the video element in the document, you don't need that, you just need to supply your `video` variable:


if(!video){
            video = document.createElement( 'video' );
            //video.width = 2048;
           // video.height = 1024;
            video.autoplay = true;
            video.loop = true;
            video.crossOrigin = '';
            video.preload = 'auto';
            video.setAttribute('webkit-playsinline', 'webkit-playsinline');


        }

        video.src = cdnPrefix + "/"+ sceneObject.video;

        makeVideoPlayableInline(video);
```

**Comment by binarykitchen** [comment]
@bfred-it why is `video.setAttribute('webkit-playsinline', 'webkit-playsinline');` required?

**Comment by bfred-it** [comment]
It isn't

**Comment by binarykitchen** [comment]
k, stupid question i guess then ;)
