### ISSUE TITLE
Could you offer the official minified file?

### ISSUE THREAD

**Issue by NiniHsu** [bfred-it/iphone-inline-video#94]
Hi, @bfred-it . I am the member of cdnjs project. We want to host this library. There is a question want to ask. I got a syntax error when I try to minify `iphone-inline-video.es-modules.js`. Could you offer the official minified file(`iphone-inline-video.es-modules.min.js`)?
Thanks!

cdnjs/cdnjs#9202

**Comment by bfred-it** [comment]
It's the `dist/iphone-inline-video.browser.js` file in the npm package.

<img width="469" alt="screen shot 2016-12-27 at 23 04 19" src="https://cloud.githubusercontent.com/assets/1402241/21501164/5532248c-cbfa-11e6-87a3-2f27adf9cc0c.png">
