### ISSUE TITLE
Playing multiple silent videos is not available on iOS 10

### ISSUE THREAD

**Issue by capnmidnight** [bfred-it/iphone-inline-video#96]
As the README points out, iOS 10 enabled *most* of the features of this project. However, it still doesn't support playing multiple, silent videos simultaneously. When iOS 10 devices get whitelisted to disable iphone-inline-video, we lose this functionality.

**Comment by bfred-it** [comment]
Refer to https://github.com/bfred-it/iphone-inline-video/issues/90#issuecomment-265745459

**Comment by capnmidnight** [comment]
Maybe this should be mentioned in the README, then?

**Comment by bfred-it** [comment]
In the v2 beta I simplified the usage on iPad. Can you try it and let me know how it goes?

- [v2 changelog](https://github.com/bfred-it/iphone-inline-video/blob/2.0/CHANGELOG.md)
- [v2 usage documentation](https://github.com/bfred-it/iphone-inline-video/tree/2.0#install)
- [iphone-inline-video.js](https://github.com/bfred-it/iphone-inline-video/tree/2.0/dist)
- If you use npm, you can install the beta with: `npm install iphone-inline-video@next`

**Comment by bfred-it** [comment]
v2.0.0 has been published :)

Now you can use the `everywhere: true` option, together with the `muted` attribute:

```js
enableInlineVideo(video, {
    everywhere: /iPhone|iPad|iPod/i.test(navigator.userAgent)
});
```
