### ISSUE TITLE
Platform detection not working on iOS 9.3.5?

### ISSUE THREAD

**Issue by elieux** [bfred-it/iphone-inline-video#98]
I'm trying to use this library on iOS 9.3.5, but it declines to run (on my page as well as on the demo page). My Safari seems to *not* have `MediaSource`. When I skip the whitelist, everything seems to work fine.

**Comment by bfred-it** [comment]
Does the demo work? https://bfred-it.github.io/iphone-inline-video/demo/

**Comment by bfred-it** [comment]
Fixed in 1.9.6
