### ISSUE TITLE
not working on devices pre iOS 10

### ISSUE THREAD

**Issue by Pau1fitz** [bfred-it/iphone-inline-video#99]
I am trying to use this library to implement inline videos pre `iOS10`.

This works for inline videos on `iOS10`, but not for pre `iOS10`.

Is there something basic that I am missing?

My **js** looks like this

    var video = $('video').get(0);
    makeVideoPlayableInline(video, false);
    
    video.addEventListener('touchstart', function () {
       video.play();
    });

And the **html** looks like this 

    <video src='http://www.w3schools.com/html/mov_bbb.mp4' class="video-player video-one" id="video-background" autoplay muted playsinline>
    </video>

**CSS**

    .IIV::-webkit-media-controls-play-button,
    video::-webkit-media-controls-start-playback-button {
        opacity: 0;
        pointer-events: none;
        width: 5px;
    }

**Comment by Pau1fitz** [comment]
It appears to just not work on my version of ios and safari? Is there a version of ios and safari that it wont work on? 

I am using v 8.3 of iOS and v600.1.4 of safari

**Comment by bfred-it** [comment]
Sorry, can you test the latest version? 1.9.5 wasn't working

**Comment by Pau1fitz** [comment]
Hi, I am using this version

https://github.com/bfred-it/iphone-inline-video/blob/master/dist/iphone-inline-video.browser.js

**Comment by bfred-it** [comment]
Did you download it today? I updated it just yesterday

**Comment by Pau1fitz** [comment]
I am sure I downloaded it today. I can check again tomorrow, but fairly certain I updated it earlier today and used the code here. I can compare the versions and confirm. Anything else you think it could be?

**Comment by bfred-it** [comment]
I think that's it, I literally pushed it 14 hours ago. That exact file works on my iOS 8: 

![timeupdate](https://cloud.githubusercontent.com/assets/1402241/22045015/bb8890da-dccc-11e6-9cca-e8ac3cef0a4d.gif)

**Comment by Pau1fitz** [comment]
Thanks, that worked!
